### PR TITLE
Fix issue creating duplicate issues for dormant repositories

### LINKED ISSUE #149: The bot is creating duplicate issues for dormant repositories
**Describe the issue**

When the bot reviews existing repositories for ones that are "dormant" it should not create an issue if one already exists. Right now, it's creating duplicate.

**Additional context**

https://github.com/bcgov/env-moosetracker-ios/issues

Screen Shot 2021-05-12 at 8 34 14 AM

**Definition of done**

- [ ] If a repo already has an issue (closed or open) then it should not create any additional issues on the same subject.

### PR DESCRIPTION
**Pull request by junminahn**
closes #149

### CODE REVIEW

**Comment by junminahn** [comment]
@jleach @wenzowski @jlangy I added a fix for issue #149, please take a look and review the changes. thanks!

**Review by wenzowski — APPROVED** [review]
This reads well to me, and the new test cases make sense. Is there any additional manual testing needed before rolling out this patch? I assume we'd ideally have this merged before next bot run to prevent further duplicate issues?

**Comment by junminahn** [comment]
@wenzowski I tried my best to follow the convention this repo has for the test coverage. I also tested the feature manually on another organization from my local dev environment to make sure it does not create another one within the period of time if the issue already created.

File: src/libs/repository.ts [hunk 1]
```diff
@@ -466,20 +467,47 @@ export const remindInactiveRepository = async (
     const updatedAt = context.payload.repository.updated_at;
```
Comment (jleach) [inline src/libs/repository.ts:468]: Lets ax this space for readability.

File: src/libs/repository.ts [hunk 2]
```diff
@@ -466,20 +467,47 @@ export const remindInactiveRepository = async (
...
+      return;
+    }
+
+    // see https://docs.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests#search-by-when-an-issue-or-pull-request-was-created-or-last-updated
+    const timeSearchFrom = new Date().getTime() - ONE_DAY * INACTIVE_DAYS;
+    const timeSearchFromISO = new Date(timeSearchFrom).toISOString();
+
+    // If there is an open/closed dormant repo issue, do not create another one.
+    // The query makes sure that it only checkes the issues created within the "inactive period".
+    const query = `repo:${owner}/${repo} is:issue author:app/${BOT_NAME} created:>${timeSearchFromISO} "${ISSUE_TITLES.INACTIVE_REPO}"`;
```
Comment (jleach) [inline src/libs/repository.ts:483]: Will it matter when the issue was created when it comes to opening duplicate issues? What I do for other issues is, rather than open a duplicate, I nudge them witha  reminder comment. I don't think it will be usefull to keep opening issues that are not being addressed or am I misunderstanding the time check in the search?

File: src/libs/repository.ts [hunk 3]
```diff
@@ -466,20 +467,47 @@ export const remindInactiveRepository = async (
...
+    const issuesResponse = await context.github.search.issuesAndPullRequests({
```
Comment (jleach) [inline src/libs/repository.ts:484]: I think duplicate closed issues are ok, as a project may get a fix then become dormant for several months. But I don't think we want duplicate `open` issues. Can we add a status check?

**Review by jleach — CHANGES_REQUESTED** [review]
I think we need to refine the search a bit - no? Only ever have 1 issue open regardless of how old it is; if its open then add a reminder comment (see existing code) rather than creating another issue. Closed issues are irrelevent as an issue may get some commits then go dormant then get commits then get domrant....

**Comment by jleach** [comment]
@junminahn Checked the code, the bot will automatically ask for an issue to be updated if it gets stale. See `      requestUpdateForMyIssues(context, owner, repo)`

File: src/libs/repository.ts (hunk 2 above)
Comment (jleach) [reply src/libs/repository.ts:483]: This query might work well:

```javascript
    const query = `repo:${owner}/${repo} is:open is:issue author:app/${BOT_NAME} "${ISSUE_TITLES.INACTIVE_REPO}"`;
```

Comment (junminahn) [reply src/libs/repository.ts:483]: I think we still should query for `open` and `closed` both otherwise, as the maintainer closes the issue they will get another one the next day, as the `updated_at` will be the same.

Comment (jleach) [reply src/libs/repository.ts:483]: Git it. If I understand correctly, activity on issues does not impact when a repo was last updated.

Comment (junminahn) [reply src/libs/repository.ts:483]: also without `created:>${timeSearchFromISO}` in the query, the bot won't create another one for good.
what we expected from this fix is to create one if the repo has not been updated anything in the repo for 180 days including the action of `closing` the old reminder issue.

**Comment by junminahn** [comment]
@jleach Thank you for your review and I think it would be very helpful to break down the all possible scenarios we could have:
1. The repo has been updated within 180days.
1. The repo is dormant for over 180days without an open/closed dormant issue created before.
1. The repo is dormant for over 180days with an open dormant issue within 180days.
1. The repo is dormant for over 180days with an open dormant issue before 180days.
1. The repo is dormant for over 180days with a closed dormant issue within 180days.
1. The repo is dormant for over 180days with a closed dormant issue before 180days.

File: src/libs/repository.ts (hunk 1 above)
Comment (junminahn) [reply src/libs/repository.ts:468]: I will remove the new line!

File: src/libs/repository.ts (hunk 2 above)
Comment (jleach) [reply src/libs/repository.ts:483]: @junminahn Are you able to rename `timeSearchFromISO` to `timeSearchFromAsISO` plus remove he space. I'll test it a little agains my demo org once the this is done and the space change above. Ty.

Comment (junminahn) [reply src/libs/repository.ts:483]: yes, I just tested again that `commenting on issues` and `closing issues` does not affect the `updated_at` field of repositories.

Comment (junminahn) [reply src/libs/repository.ts]: @jleach I just pushed changes to remove the `newline` and change `timeSearchFromISO` to `timeSearchFromAsISO`.
please let me know if there is something else you want me to change before you testing on your test environment.

**Comment by jleach** [comment]
@junminahn 

> * The repo has been updated within 180days.
> * The repo is dormant for over 180days without an open/closed dormant issue created before.
> * The repo is dormant for over 180days with an open dormant issue within 180days.
> * The repo is dormant for over 180days with an open dormant issue before 180days.
> * The repo is dormant for over 180days with a closed dormant issue within 180days.
> * The repo is dormant for over 180days with a closed dormant issue before 180days.

Not sure what "before" means in this context. Is there another word that would clarify. I'm reading it as "more than 180 days old"?

There are only two cases where it should ever open an issue:

1. The repo is dormant for over 180 days without an open/closed dormant issue created before.
2. The repo is dormant for over 180 days with a closed dormant issue **more than** 180 days **old**.

What I think will happen with the current logic, is that it will keep opening dormant issues (duplicates) every 180 days. I need to let my current test repo get a bit older before I can confirm. Right now the bot will recognize its own issues have gone stale and add a comment requesting an update. This is much better than creating duplicate issues IMHO.

**Comment by junminahn** [comment]
> @junminahn
> 
> > * The repo has been updated within 180days.
> > * The repo is dormant for over 180days without an open/closed dormant issue created before.
> > * The repo is dormant for over 180days with an open dormant issue within 180days.
> > * The repo is dormant for over 180days with an open dormant issue before 180days.
> > * The repo is dormant for over 180days with a closed dormant issue within 180days.
> > * The repo is dormant for over 180days with a closed dormant issue before 180days.
> 
> Not sure what "before" means in this context. Is there another word that would clarify. I'm reading it as "more than 180 days old"?
> 
> There are only two cases where it should ever open an issue:
> 
> 1. The repo is dormant for over 180 days without an open/closed dormant issue created before.
> 2. The repo is dormant for over 180 days with a closed dormant issue.
> 
> What I think will happen with the current logic, is that it will keep opening dormant issues (duplicates) every 180 days. I need to let my current test repo get a bit older before I can confirm. Also, for point 2 above, you could add another 180 days to the check but if the team has not addressed the issue then its fare game for another issue to be created.
> 
> Right now the bot will recognize its own issues have gone stale and add a comment requesting an update. This is much better than creating duplicate issues IMHO.

Thank you for your insights! Creating the issue every 180 days for repositories not maintained was the original intention, but we hear you that the reomountie makes comments instead for other cases. I believe that it is more design decision.
We are working on the feature proposal to cover all scenarios with edge cases and go through the approval process to take effect.

Is there any chance to merge this PR to avoid creating further duplicate issues before that is ready?

**Comment by junminahn** [comment]
@jleach We managed to draft a feature request tightly related to this issue. It would be very helpful if you have a chance to take a look.
https://github.com/bcgov/github-optimization/issues/39

**Comment by jleach** [comment]
I have it a test. This will create duplicate issues every `INACTIVE_DAYS` days. I think we just need to remove `created:>${timeSearchFromAsISO}` from the query and add `is:open` to tick off the first part of this feature.

**Comment by junminahn** [comment]
@jleach I am more concerned that if we search for open issues only, then as the owner closes the issue, they will get the issue next day again.

**Comment by jleach** [comment]
Ok, let's either move forward with this feature and get 'er done or back out the feature and you can work on it at your leisure. Right now its in a broken state and that's no good. Ty.

**Comment by junminahn** [comment]
@jleach we had a discussion around https://github.com/bcgov/github-optimization/issues/39 and https://github.com/bcgov/github-optimization/issues/93 to proceed https://github.com/bcgov/github-optimization/issues/39 before https://github.com/bcgov/github-optimization/issues/93. Once you are happy with the feature (mainly the first scenario as the second scenario is the current behaviour of repomountie already), we will proceed to implement the feature and update this or to have the feature in.

**Comment by junminahn** [comment]
@jleach @wenzowski @jlangy We updated the pr to meet the first scenario of https://github.com/bcgov/github-optimization/issues/39

**Review by jlangy — APPROVED** [review]

**Comment by jleach** [comment]
@junminahn Beside my name as a reviewer there is  "re-request review" button. Can you hit that for me? It will kick start the PR review process for me (assuming you've made all the changes you need to). Ty,

**Comment by junminahn** [comment]
and this is the pseudo-code for the logic to create a new `dormant` issue.
```
if repo last update date >= 180days
    and not archived
    and no open dormant issue
    and (no closed dormant issue 
         or (has closed dormant issue and the issue create date >= 180 days))
    {
        creates dormant issue
    }
```

**Comment by jlangy** [comment]
@jleach I know things are a bit hectic right now, if there is anything further needed for this or for #151 that we can do to help get them landed please let us know, would love to help get it to a completed state

**Review by jleach — APPROVED** [review]

**Review by jleach — APPROVED** [review]
Looks good. Tested and does not seem to be creating duplicates also is allowing reminder logic to execute. Ship it.
